modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]] #mandatory
modId="endless_sword"
version="1.16.5-0.0.3"
displayName="ES"
authors="yuo"
logoFile=""
description='''
宇宙最强之刃——万物终结.无尽星空 (うちゅう最強刃)。1.16.5
'''
[[dependencies.endless_sword]]
    modId="endless"
    mandatory=true
    versionRange="[1.16.5-1.5.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.endless_sword]]
    modId="slashblade"
    mandatory=true
    versionRange="[0.0.12,)"
    ordering="NONE"
    side="BOTH"